MvsCoreLinqToSQL/Models/Empleado.cs
namespace MvsCoreLinqToSQL.Models
{
    public class Empleado
    {
        public int IdEmpleado { get; set; }
        public string Apellido { get; set; }
        public string Oficio { get; set; }
        public int Salario { get; set; }
        public int IdDepartamento { get; set; }
    }
}

MvsCoreLinqToSQL/Models/Enfermo.cs
namespace MvsCoreLinqToSQL.Models
{
    public class Enfermo
    {
        public string Inscripcion { get; set; }
        public string Apellido { get; set; }
        public string Direccion { get; set; }
        public DateTime FechaNacimiento { get; set; }
        public string Sexo { get; set; }
        public string NumSegSoc { get; set; }
    }
}

MvsCoreLinqToSQL/Models/ErrorViewModel.cs
namespace MvsCoreLinqToSQL.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

MvsCoreLinqToSQL/Models/ResumenEmpleado.cs
namespace MvsCoreLinqToSQL.Models
{
    public class ResumenEmpleado
    {
        public int Personas { get; set; }
        public int MaximoSalario { get; set; }
        public double MediaSalarial { get; set; }
        public List<Empleado> Empleados { get; set; }
    }
}

MvsCoreLinqToSQL/Controllers/EmpleadosController.cs
using Microsoft.AspNetCore.Mvc;
using MvsCoreLinqToSQL.Models;
using MvsCoreLinqToSQL.Repositories;

namespace MvsCoreLinqToSQL.Controllers
{
    public class EmpleadosController : Controller
    {
        RepositoryEmpleados repo;

        public EmpleadosController()
        {
            this.repo = new RepositoryEmpleados();
        }

        public IActionResult Index()
        {
            List<Empleado> empleados = this.repo.GetEmpleados();
            return View(empleados);
        }

        public IActionResult Details(int idempleado)
        {
            Empleado empleado = this.repo.FindEmpleado(idempleado);
            return View(empleado);
        }

        public IActionResult BuscadorEmpleados()
        {
            return View();
        }

        [HttpPost]
        public IActionResult BuscadorEmpleados(string oficio, int salario)
        {
            List<Empleado> empleados = this.repo.GetEmpleadosOficioSalario(oficio, salario);

            if (empleados == null)
            {
                ViewData["MENSAJE"] = "No existen empleados con oficio "
                    + oficio + " y salario superior o igual " + salario;
                return View();
            }
            else
            {
                return View(empleados);
            }            
        }

        public IActionResult EmpleadosOficio()
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            return View();
        }

        [HttpPost]
        public IActionResult EmpleadosOficio(string oficio)
        {
            ViewData["OFICIOS"] = this.repo.GetOficios();
            ResumenEmpleado resumen = this.repo.GetEmpleadosOficio(oficio);
            return View(resumen);
        }
    }
}

MvsCoreLinqToSQL/Controllers/EnfermosController.cs
using Microsoft.AspNetCore.Mvc;
using MvsCoreLinqToSQL.Models;
using MvsCoreLinqToSQL.Repositories;

namespace MvsCoreLinqToSQL.Controllers
{
    public class EnfermosController : Controller
    {
        RepositoryEnfermo repo;

        public EnfermosController()
        {
            this.repo = new RepositoryEnfermo();
        }

        public IActionResult Index()
        {
            List<Enfermo> enfermos = this.repo.GetEnfermos();
            return View(enfermos);
        }

        public IActionResult Details(string inscripcion)
        {
            Enfermo enfermo = this.repo.FindEnfermo(inscripcion);
            return View(enfermo);
        }

        public async Task<IActionResult> Delete(string inscripcion)
        {
            await this.repo.DeleteEnfermo(inscripcion);
            return RedirectToAction("Index");
        }
    }
}

MvsCoreLinqToSQL/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using MvsCoreLinqToSQL.Models;

namespace MvsCoreLinqToSQL.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

MvsCoreLinqToSQL/Views/Empleados/BuscadorEmpleados.cshtml
@model List<Empleado>

<h1>Buscador Linq To SQL</h1>

<form method="post">
	<label>Oficio:</label>
	<input type="text" name="oficio" class="form-control" />
	<label>Salario:</label>
	<input type="text" name="salario" class="form-control" />
	<br />
	<button class="btn btn-info">
		Buscar empleados
	</button>
</form>

<h2 style="color:red">
	@ViewData["MENSAJE"]
</h2>

@if (Model != null){
	<table class="table table-bordered table-striped">
		<thead>
			<tr>
				<th>Apellido</th>
				<th>Oficio</th>
				<th>Salario</th>
			</tr>
		</thead>
		<tbody>
			@foreach (Empleado empleado in Model)
			{
				<tr>
					<td>@empleado.Apellido</td>
					<td>@empleado.Oficio</td>
					<td>@empleado.Salario</td>
				</tr>
			}
		</tbody>
	</table>
}

MvsCoreLinqToSQL/Views/Empleados/Details.cshtml
@model Empleado

<h1>Details</h1>

<p>
	<a asp-controller="Empleados"
	   asp-action="Index"
	   class="btn btn-outline-dark">
		Back to list
	</a>
</p>

<ul class="list-group">
	<li class="list-group-item">
		@Model.Apellido
	</li>
	<li class="list-group-item">
		@Model.Oficio
	</li>
	<li class="list-group-item">
		@Model.Salario
	</li>
	<li class="list-group-item">
		@Model.IdDepartamento
	</li>
</ul>

MvsCoreLinqToSQL/Views/Empleados/EmpleadosOficio.cshtml
@model ResumenEmpleado

@{
	List<string> oficios = ViewData["OFICIOS"] as List<string>;
}

<h1>Lambda expression Linq</h1>

<form method="post">
	<label>Oficio:</label>
	@* <input type="text" name="oficio" class="form-control" /> *@
	<select name="oficio" class="form-control">
		@foreach (string oficio in oficios){
			<option value="@oficio">@oficio</option>
		}
	</select>
	<br />
	<button class="btn btn-info">
		Buscar empleados
	</button>
</form>

@if (Model != null){
	<hr />
	<ul class="list-group">
		<li class="list-group-item">
			Personas: @Model.Personas
		</li>
		<li class="list-group-item">
			Máximo salario: @Model.MaximoSalario
		</li>
		<li class="list-group-item">
			Media salarial: @Model.MediaSalarial
		</li>
	</ul>
	<br />
	<table class="table table-striped">
		<thead>
			<tr>
				<th>Apellido</th>
				<th>Oficio</th>
				<th>Salario</th>
			</tr>
		</thead>
		<tbody>
			@foreach (Empleado empleado in Model.Empleados){
				<tr>
					<td>@empleado.Apellido</td>
					<td>@empleado.Oficio</td>
					<td>@empleado.Salario</td>
				</tr>
			}
		</tbody>
	</table>
}

MvsCoreLinqToSQL/Views/Empleados/Index.cshtml
@model List<Empleado>

<h1>Linq Empleados</h1>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Apellido</th>
			<th>Oficio</th>
			<th>Salario</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (Empleado empleado in Model){
			<tr>
				<td>@empleado.Apellido</td>
				<td>@empleado.Oficio</td>
				<td>@empleado.Salario</td>
				<td>
					<a asp-controller="Empleados"
						asp-action="Details"
						asp-route-idempleado="@empleado.IdEmpleado"
						class="btn btn-info">
						Details
					</a>
				</td>
			</tr>
		}
	</tbody>
</table>

MvsCoreLinqToSQL/Views/Enfermos/Details.cshtml
@model Enfermo

<h1>Details</h1>

<p>
	<a asp-controller="Enfermos"
	   asp-action="Index"
	   class="btn btn-outline-dark">
		Back to list
	</a>
</p>

<ul class="list-group">
	<li class="list-group-item">
		<strong>Inscripción:</strong> @Model.Inscripcion
	</li>
	<li class="list-group-item">
		<strong>Apellido:</strong> @Model.Apellido
	</li>
	<li class="list-group-item">
		<strong>Dirección:</strong> @Model.Direccion
	</li>
	<li class="list-group-item">
		<strong>Fecha de nacimiento:</strong> @Model.FechaNacimiento
	</li>
	<li class="list-group-item">
		<strong>Sexo:</strong> @Model.Sexo
	</li>
	<li class="list-group-item">
		<strong>Número Seguridad Social:</strong> @Model.NumSegSoc
	</li>
</ul>

MvsCoreLinqToSQL/Views/Enfermos/Index.cshtml
@model List<Enfermo>

<h1>Linq Enfermos</h1>

<table class="table table-bordered table-striped">
	<thead>
		<tr>
			<th>Apellido</th>
			<th>Dirección</th>
			<th>Fecha Nacimiento</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@foreach (Enfermo enfermo in Model)
		{
				<tr>
					<td>@enfermo.Apellido</td>
					<td>@enfermo.Direccion</td>
					<td>@enfermo.FechaNacimiento</td>
					<td>
						<a asp-controller="Enfermos"
							asp-action="Details"
							asp-route-inscripcion="@enfermo.Inscripcion"
							class="btn btn-info">
							Details
						</a>
						<a asp-controller="Enfermos"
						   asp-action="Delete"
						   asp-route-inscripcion="@enfermo.Inscripcion"
						   class="btn btn-danger">
							Delete
						</a>
					</td>
				</tr>
		}
	</tbody>
</table>

MvsCoreLinqToSQL/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://learn.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

MvsCoreLinqToSQL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MvsCoreLinqToSQL</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/MvsCoreLinqToSQL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">
                    <img src="~/images/deadpool.jpg" style="width:50px; height:80px" />
                </a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="Index">Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="BuscadorEmpleados">Buscar empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Empleados" asp-action="EmpleadosOficio">Lambda Empleados</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Enfermos" asp-action="Index">Enfermos</a>
                        </li>                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - MvsCoreLinqToSQL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>